//For About Us page
document.querySelector('.abt-btn').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.remove('remove-info')
    ext.classList.add('remove-info')
    comm.classList.add('remove-info')
})
document.querySelector('.ext-btn').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.add('remove-info')
    ext.classList.remove('remove-info')
    comm.classList.add('remove-info')
})
document.querySelector('.comm-btn').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.add('remove-info')
    ext.classList.add('remove-info')
    comm.classList.remove('remove-info')
})
document.querySelector('.abt-btn-1').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.remove('remove-info')
    ext.classList.add('remove-info')
    comm.classList.add('remove-info')
})
document.querySelector('.ext-btn-1').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.add('remove-info')
    ext.classList.remove('remove-info')
    comm.classList.add('remove-info')
})
document.querySelector('.comm-btn-1').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.add('remove-info')
    ext.classList.add('remove-info')
    comm.classList.remove('remove-info')
})
//For About Us page
document.querySelector('.abt-btn-2').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.remove('remove-info')
    ext.classList.add('remove-info')
    comm.classList.add('remove-info')
})
document.querySelector('.ext-btn-2').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.add('remove-info')
    ext.classList.remove('remove-info')
    comm.classList.add('remove-info')
})
document.querySelector('.comm-btn-2').addEventListener('click', () => {
    const abt = document.querySelector('.abt-art')
    const ext = document.querySelector('.exec-art')
    const comm = document.querySelector('.comm-art')
    abt.classList.add('remove-info')
    ext.classList.add('remove-info')
    comm.classList.remove('remove-info')
})